### ISSUE TITLE
[Help] build on macOS

### ISSUE THREAD

**Issue by thomasRademaker** [dogecoinfoundation/libdogecoin#116]
have any of the foundation devs been able to build on macOS?
I'm not a C dev, so I don't know if my issues are related to the code or if it is just my lack of knowledge for building C codebases. 

Long story short, I want to get some Swift bindings built so libdogecoin can be used in iOS apps.

And if there is a better place to get support other than opening a GitHub issue, please let me know.

**Comment by edtubbs** [comment]
yes, some of the devs have experience building on recent macOS but wondering if you could provide more information about your configuration or any specific issues you've encountered.  sounds very interesting, thanks!

**Comment by michilumin** [comment]
I generally have maintained some instructions on Core using Brew and xcode essentials to do native builds; I can do that here as well -- 

Are you running M1/M2 or x86/Intel mac? Unfortunately at this point in time that makes a difference; but I can do a step by step. And are you wanting to produce a .dylib or are you hoping to bring it into the full XCode suite and have it built statically with your Swift project?
