### ISSUE TITLE
Main branch is set 0.1.1-dev not main

### ISSUE THREAD

**Issue by alamshafil** [dogecoinfoundation/libdogecoin#139]
The GitHub page main branch is set to `0.1.1-dev` and not `main`. I am assuming the `main` branch is the stable branch since it is on `0.1.2` which has been released. 

Changing the main branch to `main` would be helpful for those who clone the repo directly, without specifying the branch, to get the latest stable branch (which is `0.1.2` but they would have got `0.1.1`).

This is not a issue for me, but I feel like it would be helpful to update the main branch . If not possible and could cause issues, then feel free to close this issue.

**Comment by xanimo** [comment]
agreed. i'll work on this but may need to wait till next week to update (not sure yet if i have appropriate permissions for managing the default branches).

**Comment by xanimo** [comment]
so we decided to default for the latest development branch since that's what we're all working on now. hope this is a fair in between.
