### ISSUE TITLE
[bug] `getDerivedHDAddress` and `getDerivedHDAddressByPath` return keys, not addresses

### ISSUE THREAD

**Issue by chromatic** [dogecoinfoundation/libdogecoin#152]
# Bug Report

**Current behavior:**

In libdogecoin 1.2, the functions `getDerivedHDAddress` and `getDerivedHDAddressByPath` return keys, not addresses. Compare the functions that populate the outparams to that of `getDerivedHDAddressFromMnemonic`.

**Expected behavior**

Based on the function names, I expect all three functions to return values of the same type. While I see the value of returning public keys, I'd rather use different functions to do so.

Note that the tests explicitly test for this behavior.

**Comment by xanimo** [comment]
yeah thanks for pointing that out. we're definitely going to update the named function misnomers in 0.1.3.
