### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by kosmoPAP** [dogecoinfoundation/libdogecoin#2]
Dear all,

i tried contacting Michi/Tim/Ross to get added to the libdogecoin team on GitHub and the Foundation discord serverbut got no answer, since i do not find any other way to get in touch with you, i am dropping this issue.

Thanks

**Comment by DrinoSan** [comment]
I would also be very interested in contributing somehow.

**Comment by tjstebbing** [comment]
Oh my goodness I'm so sorry I missed this!  Can you msg me on Discord (tjstebbing#5250)  or email tim at dogecoin com and I'll send you an invite link to the discord server so you can join the discussion, again apologies I'll be checking issues here frequently from now on.

**Comment by xanimo** [comment]
assuming this got handled.
