### ISSUE TITLE
[bug] Documentation/Example Code Mismatch for Derive Address Functions

### ISSUE THREAD

**Issue by chromatic** [dogecoinfoundation/libdogecoin#216]
# Bug Report

**Current behavior:**

The example code for derived key functions suggests that the functions return keys, but they appear to return addresses instead, as they return the result of calling `dogecoin_hdnode_get_p2pkh_address` -- which returns a Base58-encoded address.

**Expected behavior**

Given the names of these functions, I think returning addresses is correct and intended behavior, so the example code should be updated. (A previous version of my bindings relied on returning keys, not addresses, but I'm happy to correct this.)

Should functions exist to return derived keys? I have no current use for them.

**Comment by edtubbs** [comment]
Thanks! Agreed, I'll take a look and update the example. 

Account level public keys in BIP44 are useful for deriving addresses separate from the private key.
