### ISSUE TITLE
Build docs

### ISSUE THREAD

**Issue by tuckbick** [dogecoinfoundation/libdogecoin#28]
Hi team! Thank you for working hard on everything you've done so far. 🐕 

I have 10+ years under my belt working with Node.js and have been curious about building the Node bindings. However, I don't have much experience writing C code.
Whether or not I could contribute something worth any value is debatable, but in any case, if I wanted to dabble, I don't see any documentation on how to build the project. Is this something that's on the radar already?

**Comment by xanimo** [comment]
> Hi team! Thank you for working hard on everything you've done so far. 🐕 
> 
> I have 10+ years under my belt working with Node.js and have been curious about building the Node bindings. However, I don't have much experience writing C code.
> Whether or not I could contribute something worth any value is debatable, but in any case, if I wanted to dabble, I don't see any documentation on how to build the project. Is this something that's on the radar already?
> 
> 

Hi, yes documentation is on the way, will be working on that this week. In the meantime here are instructions for linux (windows/mac untested by me at least...😅):

debian/ubuntu:
```
sudo apt-get install autoconf automake libtool build-essential libevent-dev
```
 openbsd:
```
sudo pkg_add autoconf automake libtool libevent
```
then:
```
./autogen.sh 
./configure 
make check
```

If linux is not applicable please let me know what your os is and i'll take a look into how to get you up and running later today!

**Comment by tuckbick** [comment]
I primarily work on mac, but I can make do with linux for now. Thank you so much for the quick response!

**Comment by tuckbick** [comment]
On my mac I used brew to install some (maybe all?) dependencies. Then I was able to run the build commands you mentioned!

```sh
brew install autoconf automake libtool

./autogen.sh 
./configure 
make check
```

**Comment by tuckbick** [comment]
Not sure where else I can ask for help... but [I've started](https://github.com/tuckbick/libdogecoin/commit/e4e13344609f1fd0564ea4faaffb311459dabb5c) on the node bindings. If anyone has ideas on how to best configure [binding.gyp](https://github.com/tuckbick/libdogecoin/commit/e4e13344609f1fd0564ea4faaffb311459dabb5c#diff-afc96547744bc195caeb51fa563551cf38ebdcb2cb0822d0bde481ac87e52297) so that my C file can [recognize functions from libdogecoin](https://github.com/tuckbick/libdogecoin/commit/e4e13344609f1fd0564ea4faaffb311459dabb5c#diff-fd96fe67e62553d8a5ed85c254a3f600c263422a3288e5570ad57693ed0ca589R10-R11), I would really appreciate it!

**Comment by tjstebbing** [comment]
I've been wondering if generating web assembly builds would be a useful solution for node/deno/web/rust/etc  ? Would be great to get folks thoughts on that.

**Comment by xanimo** [comment]
> Not sure where else I can ask for help... but [I've started](https://github.com/tuckbick/libdogecoin/commit/e4e13344609f1fd0564ea4faaffb311459dabb5c) on the node bindings. If anyone has ideas on how to best configure [binding.gyp](https://github.com/tuckbick/libdogecoin/commit/e4e13344609f1fd0564ea4faaffb311459dabb5c#diff-afc96547744bc195caeb51fa563551cf38ebdcb2cb0822d0bde481ac87e52297) so that my C file can [recognize functions from libdogecoin](https://github.com/tuckbick/libdogecoin/commit/e4e13344609f1fd0564ea4faaffb311459dabb5c#diff-fd96fe67e62553d8a5ed85c254a3f600c263422a3288e5570ad57693ed0ca589R10-R11), I would really appreciate it!

Apologies for delay. Will look into this and to your point Tim, yes I think would be useful absolutely :)

**Comment by tuckbick** [comment]
Ah! Agreed, a wasm build would make things much simpler and probably eliminate a lot of the code I was having to write.

**Comment by xanimo** [comment]
leaving open until docs are in ship shape.
