### ISSUE TITLE
make check fails. char array too small

### ISSUE THREAD

**Issue by DrinoSan** [dogecoinfoundation/libdogecoin#30]
When I run the "make check" command the tests don't run through.

```  
CC       test/tests-address_tests.o
CCLD     tests
/Library/Developer/CommandLineTools/usr/bin/make  check-TESTS
FAILED - test_address() - Line 30
	Expect: 	1
	Receive:	0
/bin/sh: line 1: 87994 Abort trap: 6           ${dir}$tst
FAIL: tests
=========================================================================
1 of 1 test failed
Please report to https://github.com/dogecoinfoundation/libdogecoin/issues
=========================================================================
make[2]: *** [check-TESTS] Error 1
make[1]: *** [check-am] Error 2
make: *** [check-recursive] Error 1
```

By increasing the array size to 35 the tests pass.

```
char p2pkh_pubkey_main[33];   ----> char p2pkh_pubkey_main[35]; 
char p2pkh_pubkey_test[33];   ----> char p2pkh_pubkey_test[35];
```

Running on a Mac m1.

**Comment by xanimo** [comment]
Good find! Curious how it passes CI but I'm assuming this is because you're building natively on mac? While I investigate further let me know if you're planning on submitting a PR. Thanks!

**Comment by DrinoSan** [comment]
Yeah sure, I will submit a PR, I was just trying to find out what exactly causes the problem. If I find it, I will come back to you.

I will change the size to 35 and create the PR, hope that's fine :)

**Comment by xanimo** [comment]
I will likewise share my findings and that sounds great! Thanks again!

**Comment by xanimo** [comment]
Will keep open for discussion on why it failed after triaging is complete :3
