### ISSUE TITLE
[feat] PyPi libdogecoin packages

### ISSUE THREAD

**Issue by just-an-dev** [dogecoinfoundation/libdogecoin#61]
# Feature Request

**Describe the Feature Request**
Provide the python wrapper on PyPi to facilitate integration

**Describe Preferred Solution**
Be able to use `pip install` command to install libdogecoin wrapper

**Describe Alternatives**

**Related Code**

**Additional Context**

**Comment by xanimo** [comment]
> # Feature Request
> 
> **Describe the Feature Request** Provide the python wrapper on PyPi to facilitate integration
> 
> **Describe Preferred Solution** Be able to use `pip install` command to install libdogecoin wrapper
> 
> **Describe Alternatives**
> 
> **Related Code**
> 
> **Additional Context**

pypi module already in the works, just have to touch base with @jaxlotl tomorrow on current status. will keep you posted :)

**Comment by xanimo** [comment]
@just-an-dev long overdue and my sincere apologies for the delay. PyPi has a bit of a learning curve with regards to fixing mistakes so I had to forge ahead with a post1 prefix for the multi-arch wheels earlier this month...however it is up: https://pypi.org/project/libdogecoin/

Feedback greatly appreciated but no worries if not.
