### ISSUE TITLE
[feat] Export a symbol indicating network support

### ISSUE THREAD

**Issue by chromatic** [dogecoinfoundation/libdogecoin#66]
# Feature Request

**Describe the Feature Request**

If `libdogecoin` is configured and built without network support, multiple functions and features are not available. Library binding authors should be able to determine that this is the case by inspecting the library's exports during dynamic loading. (Static loading has other solutions.)

While it's possible to probe the library's exported symbols for an API that should only be present when networking is built, there's no canonical way to probe for this. For example, I've experimented with probing for `dogecoin_node_new()`, but that feels like implicit behavior I'm uncomfortable relying on.

**Describe Preferred Solution**

Export and document a symbol annotated with `DOGECOIN_API` which indicates the state of compile-time features, such as `LIBDOGECOIN_HAS_NETWORKING`. I have no preference as to the name; this is an example of how explicit I'd like to be.

**Describe Alternatives**

As an alternative solution, documenting a single, canonical function that will only be present in and exported from the library as a probe target will work.

I can provide example code from the Perl or Python bindings if needed to demonstrate how binding authors might use this behavior.

**Comment by xanimo** [comment]
> 

Apologies for the delay! So we have this flag already which is found in src/libdogecoin-config.h and src/libdogecoin-config.h.in that are auto generated on build:
```
/* Define to 1 to enable net compilation */
#define WITH_NET 1
```
and
```
/* Define to 1 to enable net compilation */
#undef WITH_NET
```
which is set in configure.ac:
```
AC_ARG_ENABLE([net],
  [AS_HELP_STRING([--disable-net],
  [disable net functions])],
  [with_net=$enableval],
  [with_net=yes])
...
if test "x$with_net" = xyes; then
  AC_DEFINE_UNQUOTED([WITH_NET],[1],[Define to 1 to enable net compilation])
fi
...
AM_CONDITIONAL([WITH_NET], [test "x$with_net" = "xyes"])
```

Is this more or less what you were looking for? And would it be possible to see the example code for Perl or Python bindings?

**Comment by chromatic** [comment]
I've rethought this, and it'd be okay for my bindings to call a function in `libdogecoin` like `dogecoin_network_enabled` or `dogecoin_network_support` and check a boolean return value.

You can see the bindings in [Finance/Libdogecoin/FFI.pm](https://github.com/chromatic/Finance-libdogecoin/blob/main/lib/Finance/Libdogecoin/FFI.pm#L191-L198). It's not very complex.

**Comment by xanimo** [comment]
> I've rethought this, and it'd be okay for my bindings to call a function in `libdogecoin` like `dogecoin_network_enabled` or `dogecoin_network_support` and check a boolean return value.
> 
> You can see the bindings in [Finance/Libdogecoin/FFI.pm](https://github.com/chromatic/Finance-libdogecoin/blob/main/lib/Finance/Libdogecoin/FFI.pm#L191-L198). It's not very complex.

Sounds good, I'll get this in asap.

**Comment by xanimo** [comment]
@chromatic does this fit your needs? https://github.com/dogecoinfoundation/libdogecoin/pull/87
