### ISSUE TITLE
How to Build for Embedded?

### ISSUE THREAD

**Issue by nealsinger** [dogecoinfoundation/libdogecoin#70]
How do you build libdogecoin for an ARM microcontroller?  I imagine `arm-none-eabi` goes somewhere but did not see an obvious place.  Thank you!

**Comment by alamshafil** [comment]
I have limited knowledge with micro-controllers so I can't give proper instructions. You would need a compiler for your target, something like `arm-none-eabi-gcc`.

Once you git clone / download libdogecoin, you can run configure the script to cross-compile.

To do this, run:
```bash
./configure CC=/usr/bin/arm-none-eabi-gcc  CFLAGS="compiler flags go here" --host arm-none-eabi --disable-net --disable-dependency-tracking
```

Be sure that you using the proper C compiler, compiler flags, and host.

Once the script finishes without error, you can run `make` to compile.

**Comment by xanimo** [comment]
> How do you build libdogecoin for an ARM microcontroller? I imagine `arm-none-eabi` goes somewhere but did not see an obvious place. Thank you!

Hello, apologies for delay but we currently support the host triplet `arm-linux-gnueabihf`. If in the event you are using Ubuntu or Debian you can:
```
make -C depends HOST="arm-linux-gnueabihf"
./autogen.sh
./configure --prefix=`pwd`/depends/arm-linux-gnueabihf
make check
```
Let me know if you're running a different operating system or flavor and I can try to help figure out on that.

**Comment by nealsinger** [comment]
@alamshafil Thank you for the info.
@xanimo The regular Raspberry Pi single board computers that run an OS are out of stock everywhere, so I was hoping to run libdogecoin on a Raspberry Pi Pico.  If it's the case that libdogecoin needs a kernel to run, should I close this issue?

**Comment by xanimo** [comment]
> @alamshafil Thank you for the info. @xanimo The regular Raspberry Pi single board computers that run an OS are out of stock everywhere, so I was hoping to run libdogecoin on a Raspberry Pi Pico. If it's the case that libdogecoin needs a kernel to run, should I close this issue?

It's fine to keep this open in the interim until your issue is solved if you'd like to but ultimately up to you. :)
