### ISSUE TITLE
Inconsistent definition of sign_raw_transaction in docs

### ISSUE THREAD

**Issue by alamshafil** [dogecoinfoundation/libdogecoin#71]
While viewing the transactions docs, I noticed that definition of `sign_raw_transaction` was different from the one used in the example.

Docs:
https://github.com/dogecoinfoundation/libdogecoin/blob/1a33bb5b923fd9652cfd5bf4c14676e55b209123/doc/transaction.md?plain=1#L431

libdogecoin.h:
https://github.com/dogecoinfoundation/libdogecoin/blob/1a33bb5b923fd9652cfd5bf4c14676e55b209123/include/dogecoin/libdogecoin.h#L96

The docs includes `char* amount` while the header does not.

**Comment by michilumin** [comment]
Ok, yes, we removed the need for an amount string later on in the process and didn't update the documentation. Just need to remove that from the doc, as what's in the header is correct/current.
