### ISSUE TITLE
[bug] generateHDMasterPubKeypair in address.c needs helpin' on returning junk at the end of addresses.

### ISSUE THREAD

**Issue by michilumin** [dogecoinfoundation/libdogecoin#74]
# Bug Report

**Current behavior:**

generateHDMasterPubKeypair in address.c will sometimes return 'extra garbage' at the end of an address (always a pubkey, it seems.)

It does not always generate this garbage but if you populate the entire (sizeof) the addresses it will often do so. 

```
char array_that_holds_privkey[114]; //normally 51 for wif Q keys, but 111 in this case due to privkey chaincode. 114 is too much.
char array_that_holds_pubkey[36]; //this should be 34

generatePrivPubKeypair(array_that_holds_privkey, p2pkh_pubkey, 0);

memset(array_that_holds_privkey, 0xcc, sizeof(array_that_holds_privkey));
memset(array_that_holds_pubkey, 0xcc, sizeof(array_that_holds_pubkey));

generateHDMasterPubKeypair(array_that_holds_privkey, array_that_holds_pubkey, 0)


//actual returned contents of array_that_holds_privkey:
//dgpv51eADS3spNJh7yoYcdCRc5JeDzZs7TpbPMq5iZm5XgEVZLQNohKYXtr3vu5mRDo8yut5cs7x2xWHsyyjmAC4GqJo9w6WA79jKLXuP1oqeYPBb?$

//returned contents of array_that_holds_pubkey:
//DBFsQjPv6TtrGcVtjNqqmNLMMohvEW7tneZxá☺
```
 
**Expected behavior**

```

//expected returned contents of array_that_holds_privkey:
//dgpv51eADS3spNJh7yoYcdCRc5JeDzZs7TpbPMq5iZm5XgEVZLQNohKYXtr3vu5mRDo8yut5cs7x2xWHsyyjmAC4GqJo9w6WA79jKLXuP1oqeYP

//no extraneous: Bb?$

//expected returned contents of array_that_holds_pubkey:
//DBFsQjPv6TtrGcVtjNqqmNLMMohvEW7tne

//(no extraneous Zxá☺)

```

... Zero out everything after the proper length and terminate the string, maybe?

**Steps to reproduce:**

-Set the arrays to be populated to larger than 34, 51 and 111.
-Memset them with junk, filling them to (sizeof) say 36, 53 and 114 (or 128, or 200).
-Run the function
-Call the function a few times and you'll get garbage at the end.

**Comment by michilumin** [comment]
Notes:

```
#define PRIVKEYWIFLEN 51 //WIF length for uncompressed keys is 51 and should start with Q
#define MASTERKEYLEN 111 //should be chaincode + privkey; starts with dgpv51eADS3spNJh8 or dgpv51eADS3spNJh9
#define PUBKEYLEN 34 //our mainnet addresses are 34 chars if p2pkh and start with D
```
With the current function, deviating from these can cause errors appended to the end of keys and addresses. However the function should sanitize this itself, and limit check it.

**Comment by michilumin** [comment]
WIF private key = 51 characters,  p2pkh address = 34 characters.   In the code, 128 is being used for a lot of things, which i think is only correct for hex-string representations of HD master keys..   

HD Master private keys are larger than WIF private keys, because they're "chaincode + privatekey".  It seems like after encoding, those are 111 bytes.  

Raw "hex", private keys are 256 bits so 32 bytes so 64 "0x02 hex characters",  chaincode(256bits)+rawprivatekey(256bits) = 64 bytes so 128 "0x02 hex characters" (chaincode = 256bits, + privatekey=256bits), which is why it looks like 128 is used for a lot of key fields 'maximum". 

We need to replace these with the appropriate lengths so we aren't gathering unset junk.

I changed example.c in my recent build to limit this, and errors aren't being produced.  But that memory is being dragged around and junk is being gathered internally, so this has to be limited and bounds checked.

**Comment by xanimo** [comment]
@michilumin how was this produced? I'm assuming x86_64/i686-w64-mingw32 and building the example? When running `make && valgrind -s ./tests`, I've found the lowest fixed length array I can set is 112 and 33 in `generateHDMasterPubKeypair` 🤷 but if I remember correctly, DrinoSan was encountering errors on M1 apple if set to 33 or something like that? This is on x86_64-pc-linux-gnu.

**Comment by michilumin** [comment]
Ubuntu 22.04 x86-84 linux
