### ISSUE TITLE
Generic message signing / verification functionality 

### ISSUE THREAD

**Issue by tjstebbing** [dogecoinfoundation/libdogecoin#89]
# Feature Request

The btc rpc documentation lists two calls: `signmessagewithprivkey` and `verifymessage`, the purpose of which is to sign and verify arbitrary strings. This is incredibly useful functionality for L2 projects as it allows services and features that can provably verify the origin of other data out of band with the blockchain, by using a form of on-chain identity in the future.

GigaWallet specifically wants to use this feature to sign 'invoice' payloads as part of the `doge connect` protocol, that is a request for a payment to be made, between client/server. This will allow wallets implementing `doge connect` to keep a list of approved stores (previously visited/confirmed gigawallet instances) and know if an invoice is trying to spoof them. Furthermore we intend on using the DNS hack to allow sites to list a public key that will be used to sign these messages so there's a path to providing verifiable payment invoices.. all this depends on our ability to sign and verify anything. 

**Describe Preferred Solution**
Adding convenience functions, aligned with the various libdogecoin-implemented key types, for sign/verify. 

**Describe Alternatives**
n/a

**Related Code**
n/a

**Additional Context**
https://developer.bitcoin.org/reference/rpc/signmessagewithprivkey.html
https://developer.bitcoin.org/reference/rpc/verifymessage.html

**Comment by xanimo** [comment]
Closing this out per merge of #104
